name: Rebase

on:
  schedule:
    - cron: '0 0 * * *'

   
jobs:
  build:
    strategy:
      matrix:
        branch: [lineage-21.0]

    env:
      org: "a57y17lte-dev"
      upstream_org: "LineageOS"
      repo:  "android_build"
      branch: "${{ matrix.branch }}"

    name: Automatic rebase
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Rebase
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/a57y17lte-dev/android_frameworks_base -b $branch
        cd android_frameworks_base
        git fetch https://github.com/LineageOS/android_frameworks_base.git $branch
        git rebase FETCH_HEAD
        git push -f
      env:
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USER: ${{ secrets.USERNAME }}
