name: Rebase

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      matrix: android_hardware_samsung
        branch: [android_hardware_samsung]
    name: Automatic rebase
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Rebase
      run: |
        git config --global user.name "${{ secrets.USERNAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        git clone https://"${{ secrets.USERNAME }}":"${{ secrets.TOKEN }}"@github.com/a57y17lte-dev/android_hardware_samsung.git -b ${{ matrix.branch }}
        cd android_hardware_samsung
        git fetch https://github.com/LineageOS/android_hardware_samsung.git ${{ matrix.branch }}
        git rebase FETCH_HEAD
        git push -f
